import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { FIXTURE_ARTICLES } from "@/fixtures/articles";
import { classify } from "@/lib/curation/classify";
import { classifySection } from "@/lib/curation/section";
import { coverQuery } from "@/lib/news/cover-query";
import {
  isPexelsConfigured,
  searchPexels,
  type CoverImage,
} from "@/lib/providers/pexels";

/**
 * Backfill Pexels cover images for the fixture wire (§13). Resolves a landscape
 * photo per fixture article and writes fixtures/cover-images.ts, which the read
 * layer imports statically — so the served site never calls Pexels on render
 * (§17). Re-run whenever fixtures change.
 *
 *   PEXELS_API_KEY=... pnpm tsx scripts/fetch-cover-images.ts
 *
 * With no key it exits without touching the committed map (the UI keeps drawing
 * the deterministic SVG covers).
 */

function queryFor(headline: string, dek: string | null): string {
  const c = classify(headline, dek);
  const section = classifySection({
    title: headline,
    dek,
    topics: c.topics,
    tickers: c.tickers,
  });
  const extra = c.entities[0] ?? c.tickers[0] ?? c.topics[0]?.replace(/_/g, " ") ?? "";
  return coverQuery(section, extra);
}

async function main(): Promise<void> {
  if (!isPexelsConfigured()) {
    console.log("[cover-images] PEXELS_API_KEY not set — leaving the map unchanged.");
    return;
  }

  const map: Record<number, CoverImage> = {};
  for (const a of FIXTURE_ARTICLES) {
    const query = queryFor(a.headline, a.dek);
    const cover = await searchPexels(query);
    if (cover) {
      map[a.id] = cover;
      console.log(`[cover-images] #${a.id} ← "${query}"`);
    } else {
      console.warn(`[cover-images] #${a.id} no photo for "${query}"`);
    }
  }

  const out = `import type { CoverImage } from "@/lib/providers/pexels";

/**
 * Resolved Pexels cover images for the fixture wire, keyed by article id.
 * GENERATED by scripts/fetch-cover-images.ts — do not edit by hand. Committed so
 * the served site never calls Pexels on render (§17). Missing ids fall back to
 * the deterministic on-brand SVG cover (components/news/CoverArt.tsx).
 */
export const COVER_IMAGES: Record<number, CoverImage> = ${JSON.stringify(map, null, 2)};
`;
  writeFileSync(join(process.cwd(), "fixtures", "cover-images.ts"), out, "utf8");
  console.log(`[cover-images] wrote ${Object.keys(map).length} images.`);
}

main().catch((err) => {
  console.error("[cover-images] failed:", err);
  process.exit(1);
});
