import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { FIXTURE_ARTICLES } from "@/fixtures/articles";
import { readCluster, readWire } from "@/lib/news/read";
import { generateBrief, isGroqConfigured } from "@/lib/providers/groq";
import type { ArticleBody } from "@/fixtures/articles-body";

/**
 * Generate AI-written article bodies for the wire with Groq (§13), writing
 * fixtures/articles-body.ts (keyed by the cluster's primary article id). The read
 * layer imports it statically, so the served site never calls the model on render.
 * Re-run whenever fixtures change. Original content only — never source text (§10).
 *
 *   GROQ_API_KEY=... [GROQ_MODEL=llama-3.3-70b-versatile] pnpm tsx scripts/generate-briefs.ts
 *
 * In production the same generateBrief() runs in the cluster job over ingested
 * stories, writing to the store the DB-backed read path consumes.
 */
async function main(): Promise<void> {
  if (!isGroqConfigured()) {
    console.log("[briefs] GROQ_API_KEY not set — leaving the bodies unchanged.");
    return;
  }
  const byId = new Map(FIXTURE_ARTICLES.map((a) => [a.id, a]));
  const clusters = await readWire();
  const map: Record<number, ArticleBody> = {};

  for (const c of clusters) {
    const detail = await readCluster(c.slug);
    const sources = detail?.members.map((m) => m.sourceName) ?? [];
    const brief = await generateBrief(String(c.primaryId), {
      title: c.title,
      dek: byId.get(c.primaryId)?.dek ?? null,
      section: c.section,
      tickers: c.tickers,
      sources,
    });
    if (brief) {
      map[c.primaryId] = { md: brief.body, model: brief.model };
      console.log(`[briefs] #${c.primaryId} ← ${brief.model}`);
    } else {
      console.warn(`[briefs] #${c.primaryId} no brief generated`);
    }
  }

  const out = `import type { ArticleBody } from "./articles-body-type";

/**
 * GENERATED by scripts/generate-briefs.ts (Groq). Original AI-written summaries,
 * never source text (§10). Keyed by the cluster's primary article id.
 */
export const ARTICLE_BODIES: Record<number, ArticleBody> = ${JSON.stringify(map, null, 2)};
`;
  // Note: keep the ArticleBody interface in fixtures/articles-body.ts; when this
  // script owns the file, move the interface to articles-body-type.ts first.
  writeFileSync(
    join(process.cwd(), "fixtures", "articles-body.generated.ts"),
    out,
    "utf8",
  );
  console.log(
    `[briefs] wrote ${Object.keys(map).length} bodies to fixtures/articles-body.generated.ts`,
  );
}

main().catch((err) => {
  console.error("[briefs] failed:", err);
  process.exit(1);
});
